paths:
  /users:
    get:
      description: 전체 조회
      tags: [users]
      content: application/json
      responses:
        200:
          description: 성공
    post:
      description: 회원가입
      tags: [users]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCreate'
      responses:
        200:
          description: 성공
components:
  schemas:
    UserCreate:
      type: object
      properties:
        email:
          type: string
          default: test@test.com
          description: 이메일
        password:
          type: string
          default: yoursecret